#pragma config(Sensor, in1,    autonSelectorPot, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LiftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           RightNotY,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightY,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RightDrive1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RightDrive2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Claw1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftDrive1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LeftDrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LeftY,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LeftNotY,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// DO NOT MODIFY
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

// ======== GLOBAL DEFINITIONS AND PREPROCESSOR DIRECTIVES ==========
#define LEFT_ORIENTATION -1
#define RIGHT_ORIENTATION 1

#define CUBE_MIDFIELD_AUTON 0
#define CUBE_SHORT_AUTON 1
#define SAME_SIDE_AUTON 2

// this is modified by autonomous selector buttons, to flip auton orientation.
int autonOrientation = RIGHT_ORIENTATION;

// ======== INCLUDES =========
#include "robotAPI.h"
#include "userControl.h"
#include "manageLCD.h"
#include "manageAutons.h"

void pre_auton()
{
	// DO NOT MODIFY, manages task stopping.
	bStopTasksBetweenModes = true;

	// init encoders, do not reset them elsewhere!
	SensorValue[LiftEncoder] = 0;
	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;

	//start LCD.
	startTask(LCD);
	while (true) { wait1Msec(25); }
}

task autonomous()
{
	// get the auton selector auton, and run.
	runSelectedAuton();
	while (true) { wait1Msec(25); }
}

task usercontrol()
{
	// driving controls.
	runUserControl();
	while (true) { wait1Msec(25); }
}
